bonzo/authapp/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp_views

app_name = 'authapp'

urlpatterns = [

]

bonzo/bonzo/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = "mainapp.views.page_not_found_view"

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('url/', include('urlapp.urls', namespace='url')),
    path('admin/', admin.site.urls, name='admin'),

]

bonzo/mainapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from mainapp import views as mainapp_views

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp_views.index, name='index'),
    path('404/', mainapp_views.page_not_found_view, name='404'),
    re_path(r'(?P<short_url>.{5,8})/$', mainapp_views.open_short_url, name='open_short_url'),
]

bonzo/urlapp/urls.py
from django.urls import path
from urlapp import views as urlapp_views

app_name = 'urlapp'

urlpatterns = [
    path('shorten/', urlapp_views.shorten_url, name='shorten_url'),

]

bonzo/authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class BonzoUser(AbstractUser):
    pass

bonzo/mainapp/models.py
import datetime

from django.db import models

bonzo/urlapp/models.py
from datetime import datetime

from django.db import models

from authapp.models import BonzoUser


class URL(models.Model):
    original = models.TextField(verbose_name='original link', blank=False, unique=False)
    short = models.CharField(verbose_name='short link', max_length=8, blank=False, unique=True)
    created_at = models.DateTimeField(verbose_name='created', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='updated', auto_now=True)
    last_used_at = models.DateTimeField(verbose_name='last used', blank=True, null=True)
    user = models.ForeignKey(verbose_name='user', to=BonzoUser, on_delete=models.CASCADE, related_name='urls',
                             null=True)

    def update_last_used_time(self):
        self.last_used_at = datetime.now()

bonzo/authapp/views.py
from django.shortcuts import render

# Create your views here.

bonzo/mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404

from urlapp.models import URL


def page_not_found_view(request, exception):
    return render(request, 'mainapp/404.html', status=404)


def index(request, errors=None):
    print(errors)
    context = {
        'page_title': 'главная',
    }
    return render(request, 'mainapp/index.html', context)


def open_short_url(request, short_url):
    url_model = URL
    url = get_object_or_404(url_model, short=short_url)
    original_url = url.original
    return redirect(original_url)


def duplicate_short_url_check():
    pass


def duplicate_url_check():
    pass


def get_short_url():
    pass

bonzo/urlapp/views.py
import hashlib
import random
import string

from django.http import HttpResponseRedirect
from django.shortcuts import render

import validators
from django.urls import reverse

from urlapp.models import URL


def shorten_url(request):
    context = dict()
    if request.method == 'POST':
        original_url = request.POST["url"]
        if len(original_url) and validators.url(original_url):
            short_url = get_short_url(5)
            url_obj = URL(
                original=original_url,
                short=short_url
            )
            url_obj.save()
            # context['short_url'] = f'http://bonzzo:8000/{short_url}'
            context['short_url'] = f'http://127.0.0.1:8000/{short_url}'
            return render(request, 'urlapp/url.html', context)
        else:
            # return render(request, 'mainapp/index.html', context)
            return HttpResponseRedirect(reverse('mainapp:index'))


def get_short_url(length: int):
    letters = string.ascii_letters
    short_url = ''
    while True:
        short_url = ''.join(random.choice(letters) for i in range(length))
        if not URL.objects.filter(short=short_url).first():
            break
    return short_url

bonzo/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            Bonzzo! {{ page_title|capfirst }}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href={% static "img/favicon.ico" %}>

    {% block css %}
        <link href={% static "css/bootstrap.css" %} rel="stylesheet">
        <link href={% static "css/style.css" %} rel="stylesheet">
        <link rel='stylesheet' id='prettyphoto-css' href={% static "css/prettyPhoto.css" %} type='text/css' media='all'>
        <link href={% static "css/fontello.css" %} type="text/css" rel="stylesheet">
        <link href={% static "css/fontello-ie7.css" %} type="text/css" rel="stylesheet">
        <link href={% static "css/bootstrap-responsive.css" %} rel="stylesheet">
        <style>
            body {
                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>
    {% endblock %}
    {#{% static  %}#}
    {% block js_top %}
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <script type="text/javascript" src={% static "js/jquery.js" %}></script>
        <script type="text/javascript" src={% static "js/jquery.scrollTo-1.4.2-min.js" %}></script>
        <script type="text/javascript" src={% static "js/jquery.localscroll-1.2.7-min.js" %}></script>

        <script type="text/javascript" charset="utf-8">
            $(document).ready(function () {
                $("a[rel^='prettyPhoto']").prettyPhoto();
            });
        </script>

    {% endblock %}

    {% block fonts %}
        <link href='http://fonts.googleapis.com/css?family=Quattrocento:400,700' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    {% endblock %}
</head>
<body>
<!--******************** NAVBAR ********************-->
<div class="navbar-wrapper">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span
                        class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
                <h1 class="brand"><a href="{% url 'mainapp:index' %}">Bonzzo!</a></h1>
                {#                <nav class="pull-right nav-collapse collapse">#}
                {#                    <ul id="menu-main" class="nav">#}
                {#                        <li><a title="portfolio" href="#portfolio">Portfolio</a></li>#}
                {#                        <li><a title="services" href="#services">Services</a></li>#}
                {#                        <li><a title="news" href="#news">News</a></li>#}
                {#                        <li><a title="team" href="#team">Team</a></li>#}
                {#                        <li><a title="contact" href="#contact">Contact</a></li>#}
                {#                    </ul>#}
                {#                </nav>#}
            </div>
        </div>
    </div>
</div>
<div id="top"></div>

{% block content %}

{% endblock %}

<div class="footer-wrapper">
    <div class="container">
        <footer>
            <small>&copy; 2022 All rights reserved.</small>
        </footer>
    </div>
    <!-- ./container -->
</div>

{% block js_bottom %}
    <script type="text/javascript" src={% static "js/bootstrap.js" %}></script>
    <script type="text/javascript" src={% static "js/jquery.prettyPhoto.js" %}></script>
    <script type="text/javascript" src={% static "js/site.js" %}></script>
{% endblock %}



<!--ANALYTICS CODE-->
{#<script type="text/javascript">#}
{#    var _gaq = _gaq || [];#}
{#    _gaq.push(['_setAccount', 'UA-29231762-1']);#}
{#    _gaq.push(['_setDomainName', 'dzyngiri.com']);#}
{#    _gaq.push(['_trackPageview']);#}
{##}
{#    (function () {#}
{#        var ga = document.createElement('script');#}
{#        ga.type = 'text/javascript';#}
{#        ga.async = true;#}
{#        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';#}
{#        var s = document.getElementsByTagName('script')[0];#}
{#        s.parentNode.insertBefore(ga, s);#}
{#    })();#}
{#</script>#}
</body>
</html>

bonzo/mainapp/templates/mainapp/includes/inc__features.html
<div class="scrollblock">
    <section id="feature">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <article>
                        <p>Создавайте уникальные короткие URL-адреса и обменивайтесь ими в сети.</p>
                        <p>Используйте сервис сокращения ссылок для email-переписки и общения на форумах.</p>
                    </article>
                </div>
            </div>
        </div>
    </section>
</div>
{#<hr>#}

bonzo/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <div id="headerwrap">
        <header class="clearfix">
            <h1><span>Bonzzo!</span> Сервис сокращения ссылок.</h1>
            <div class="container">
                <div class="row">
                    <form action="{% url 'urlapp:shorten_url' %}" method="post" class="span12">
                        {% csrf_token %}
                        <h2>Сократите любую ссылку до минимальной длины</h2>
                        <input type="text" name="url" placeholder="https://www.example.com" class="cform-text" size="40"
                               title="your email">
                        <input type="submit" value="Сократить" class="cform-submit">
                    </form>
                </div>
                <div class="row">
                    <div class="span12">
                        {#                        <ul class="icon">#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-pinterest-circled"></i></a></li>#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-facebook-circled"></i></a></li>#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-twitter-circled"></i></a></li>#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-gplus-circled"></i></a></li>#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-skype-circled"></i></a></li>#}
                        {#                        </ul>#}
                    </div>
                </div>
            </div>
        </header>
    </div>
    {% include 'mainapp/includes/inc__features.html' %} }}
{% endblock %}

bonzo/urlapp/templates/urlapp/url.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block js_top %}
    {{ block.super }}
    <script src={% static "js/js_actions.js" %}></script>
{% endblock %}

{% block content %}
    <!-- ******************** HeaderWrap ********************-->
    <div id="headerwrap">
        <header class="clearfix">
            <h1><span>Zonzo!</span> Сервис сокращения ссылок.</h1>
            <div class="container">
                <div class="row">
                    {% csrf_token %}
                    <h2 id="short_url">{{ short_url }}</h2>
                    <button onclick="copyShortURL()" class="cform-submit">Скопировать</button>
                </div>
                <div class="row">
                    <div class="span12">
                        {#                        <ul class="icon">#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-pinterest-circled"></i></a></li>#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-facebook-circled"></i></a></li>#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-twitter-circled"></i></a></li>#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-gplus-circled"></i></a></li>#}
                        {#                            <li><a href="#" target="_blank"><i class="icon-skype-circled"></i></a></li>#}
                        {#                        </ul>#}
                    </div>
                </div>
            </div>
        </header>
    </div>
    {% include 'mainapp/includes/inc__features.html' %} }}
{% endblock %}